directive @unique on FIELD_DEFINITION
type User {
  _id: ID
  username: String! @unique
  email: String!
  password: String!
  avatar: String
  joinDate: String
  favourites: [Post]
}

type Post {
  _id: ID
  title: String!
  imageUrl: String!
  categories: [String]!
  description: String!
  createdDate: String
  likes: Int
  createdBy: User!
  messages: [Message]
}

type Message {
  _id: ID
  messageBody: String!
  messageDate: String
  messageUser: User!
}

type Token {
  token: String!
}

type Mutation {
  addPost(
    title: String!
    imageUrl: String!
    categories: [String!]
    description: String!
    creatorId: ID!
  ): Post!
  signInUser(username: String!, password: String!): Token
  signUpUser(username: String!, email: String!, password: String!): Token
}

type Query {
  getPosts: [Post]
  getCurrentUser: User
}
